### ISSUE TITLE
[docker-compose] setup default deployment directory path as opposed to relative paths

### ISSUE THREAD

**Issue by shantanoo-desai** [shantanoo-desai/komponist#28]
## Description

A known caveat for using relative paths in the `docker-compose.<service>.yml.j2` templates e.g. `./conf/<service>`, if the host where komponist generate the dedicated files __MAY__ have a different absolute path when resolved via `docker compose config` which can cause incompatibility issues when used for remote deployment strategies.

In a nutshell, the generated `docker-compose.yml` file will have absolute paths to configuration directories that __MAY__ not exist on remote machines.

**Comment by shantanoo-desai** [comment]
For a given `deploy_dir` set to `./deploy`, upon executing the `generate_stack.yml` on an inventory list of hosts the `deploy` directory is generated in the home directory of the remote ansible user. Assuming the default working directory is based on the ansible fact of `ansible_user_dir` using a `.` in all Docker Compose will work as the generated `docker-compose.yml` will resolve the path w.r.t. to the User directory

**Comment by shantanoo-desai** [comment]
## Decision

make `deploy_dir` optional parameter and set the default value to be `~/.komponist` in the `ansible_user_dir` using `gather_facts`

**Comment by shantanoo-desai** [comment]
## Effort

### Tasks

- [ ] `configure-grafana.yml`
- [ ] `configure-influxdbv1.yml`
- [ ] `configure-influxdbv2.yml`
- [ ] `configure-mosquiito.yml`
- [ ] `configure-nodered.yml`
- [ ] `configure-questdb.yml`
- [ ] `configure-telegraf.yml`
- [ ] `configure-timescaledb.yml`
- [ ] `configure-traefik.yml`

### Playbooks

- [ ] `generate_stack.yml`
- [ ] `boostrap_nodered.yml`
- [ ] `export_nodes_nodered.yml`

### Tests

- [ ] `test_schemas.yml`
- [ ] `test_file_contents.yml`
- [ ] `test_generated_files.yml`
- [ ] `test_generated_directories.yml`
- [ ] `test_config_nodered.yml`
- [ ] `test_config_grafana.yml`
- [ ] `test_config_traefik.yml`
- [ ] `test_config_telegraf.yml`
- [ ] `test_config_influxdb.yml`
- [ ] `test_config_mosquitto.yml`
