### ISSUE TITLE
[node-red] Jinja2 Template for `settings.js` file

### ISSUE THREAD

**Issue by shantanoo-desai** [shantanoo-desai/komponist#3]
## Description

Create a `setting.js.j2` file that comprises of Jinja2 Variables that let a user configure node-red depending on values defined in a dedicated configuration YAML file. The file __SHOULD__ be contain basic settings and should have the respective Node-RED license in its header as well as the Repo license.

## Tasks
- [x] Configure the `credentialSecret` via a Jinja2 variable. This is optional, hence comment it out if variable not set
- [x] Add Credentials as array of users to the file with their passwords encrypted via requirements in #2 
- [x] Set default Port to 1880
- [x] Set Render node-RED behind Root path `/nodered` as specified in #1 
- [x] Set additional node-RED custom HTTP APIs behind the Admin Root path above as specified in #1 
- [x] Enable `diagnostics` and `runtime` endpoints for node-RED instance management
- [x] Provide boolean values to enable / disable the node-RED Editor configuration
