### ISSUE TITLE
Configure and Setup Grafana v9.x

### ISSUE THREAD

**Issue by shantanoo-desai** [shantanoo-desai/komponist#31]
## Description

Configure Grafana using configuration files / environment variables

### Tasks

- [ ] [grafana] design Credentials YAML structure
- [ ] [grafana] design Configuration YAML structure
    - [ ] [grafana] provide configuration directory to install custom datasources, dashboards 
- [ ] [grafana] create Jinja2 Template for Compose Service file
