### ISSUE TITLE
[node-red][docker-compose] Jinja2 Template for Compose file

### ISSUE THREAD

**Issue by shantanoo-desai** [shantanoo-desai/komponist#4]
## Description

Design a Jinja2 Template called `docker-compose.nodered.yml.j2` that __SHOULD__ generate a valid compose file by using Jinja2 Variables.

### Tasks

- [x] Allow custom node-red images as opposed to image from DockerHub (Optional). Defaults to DockerHub images
- [x] Allow setting version of image (Optional). Defaults to `latest` tag
- [x] Potential use of `config` specification to mount the generated `settings.js` file
