### ISSUE TITLE
[influxdbv2] Refactor Initial Credentials insertion via Docker Secrets

### ISSUE THREAD

**Issue by shantanoo-desai** [shantanoo-desai/komponist#48]
## Description

Based on [Influxdb Docker Repo](https://github.com/influxdata/influxdata-docker/tree/539d8b4f98f31bb2c4771d8cedb4c69c87b95675) is is possible to insert the initial credentials via Docker Secrets which can be read from the respective mounted filed within the container.

The refactor resembles similarly to Grafana's Docker Compose File. The final Environment Variables will be inserted to into the main `.env` file

### Tasks

- [x] refactor Compose file for `influxdbv2` service
- [x] add initial credentials information into the `komponist.env`
- [x] remove the `influxdbv2.env` file
