### ISSUE TITLE
[timescaledb] Configure and Setup TimescaleDB

### ISSUE THREAD

**Issue by shantanoo-desai** [shantanoo-desai/komponist#53]
## Description

Introduce TimescaleDB for Komponist with following steps:

### Tasks

- [x] #54
- [x] #55
- [ ] #56
- [x] Add `docker-compose.timescaledb.yml.j2` Jinja Template
- [x] Add `configure-timescaledb.yml` task file
- [x] Add the Initial Information in `komponist.env.j2` Env Vat Template
