### ISSUE TITLE
[docker][node-red][influxdbv2] Remove `user` parameter from Docker Compose Templates

### ISSUE THREAD

**Issue by shantanoo-desai** [shantanoo-desai/komponist#88]
## Description

Having `ansible_user_id` anything other than the `uid` within the container causes __Node-RED__ and __InfluxDBv2__ to crash since during initialization phase the container tries to create directories which cannot be performed due to user id mismatches in container / host.

With resolution of #79 by using `mode` for secrets, the `user` parameter can be removed from all the Compose Templates.

Removing it from all templates would be preferable to make compose files compatible.

### Tasks

- [x] remove `user` from `docker-compose.nodered.yml.j2`
- [x] remove `user` from `docker-compose.mosquitto.yml.j2`
- [x] remove `user` from `docker-compose.influxdbv2.yml.j2`
- [x] remove `user` from `docker-compose.grafana.yml.j2`
- [x] #89
- [x] #90
