### ISSUE TITLE
[influxdbv2] consolidate directly written init env vars into `.env`

### ISSUE THREAD

**Issue by shantanoo-desai** [shantanoo-desai/komponist#93]
## Description

For Telegraf Output plugin which requires information of Bucket, Token and Organization, extract the values previously set directly in the Docker Compose template file into the `komponist.env.j2` similar to InfluxDBv2.

### Tasks

- [x] refactor `templates/services/docker-compose.influxdbv2.yml.j2`
- [x] add the respective values as env vars into `templates/komponist.env.j2`
- [x] Add the env var placeholders in the Docker Compose Template for interpolation
- [x] refactor tests for `influxdbv2` checks
